spring:
  datasource:
    url: jdbc:mysql://localhost:3306/textManger?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT &allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    propreties:
      hibernate:
        format_sql: true
server:
  port: 8181
